server:
  port: 8080

spring:
  application:
    name: user-api-microsservicos

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always


